// Generated by gencpp from file delivery_robot/r_costmap.msg
// DO NOT EDIT!


#ifndef DELIVERY_ROBOT_MESSAGE_R_COSTMAP_H
#define DELIVERY_ROBOT_MESSAGE_R_COSTMAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <delivery_robot/r_pose.h>

namespace delivery_robot
{
template <class ContainerAllocator>
struct r_costmap_
{
  typedef r_costmap_<ContainerAllocator> Type;

  r_costmap_()
    : resolution(0.0)
    , width(0)
    , height(0)
    , origin()
    , cost_value()  {
    }
  r_costmap_(const ContainerAllocator& _alloc)
    : resolution(0.0)
    , width(0)
    , height(0)
    , origin(_alloc)
    , cost_value(_alloc)  {
  (void)_alloc;
    }



   typedef double _resolution_type;
  _resolution_type resolution;

   typedef uint16_t _width_type;
  _width_type width;

   typedef uint16_t _height_type;
  _height_type height;

   typedef  ::delivery_robot::r_pose_<ContainerAllocator>  _origin_type;
  _origin_type origin;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _cost_value_type;
  _cost_value_type cost_value;





  typedef boost::shared_ptr< ::delivery_robot::r_costmap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delivery_robot::r_costmap_<ContainerAllocator> const> ConstPtr;

}; // struct r_costmap_

typedef ::delivery_robot::r_costmap_<std::allocator<void> > r_costmap;

typedef boost::shared_ptr< ::delivery_robot::r_costmap > r_costmapPtr;
typedef boost::shared_ptr< ::delivery_robot::r_costmap const> r_costmapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delivery_robot::r_costmap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delivery_robot::r_costmap_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delivery_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'delivery_robot': ['/home/azu001/catkin_ws/src/delivery_robot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'move_base_msgs': ['/home/azu001/catkin_ws/src/navigation_msgs/move_base_msgs/msg', '/home/azu001/catkin_ws/devel_isolated/move_base_msgs/share/move_base_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delivery_robot::r_costmap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery_robot::r_costmap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery_robot::r_costmap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery_robot::r_costmap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_robot::r_costmap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_robot::r_costmap_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delivery_robot::r_costmap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0391321e23650d4c155c8944c4c4170c";
  }

  static const char* value(const ::delivery_robot::r_costmap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0391321e23650d4cULL;
  static const uint64_t static_value2 = 0x155c8944c4c4170cULL;
};

template<class ContainerAllocator>
struct DataType< ::delivery_robot::r_costmap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delivery_robot/r_costmap";
  }

  static const char* value(const ::delivery_robot::r_costmap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delivery_robot::r_costmap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 resolution\n\
uint16 width\n\
uint16 height\n\
r_pose origin\n\
uint8[] cost_value\n\
\n\
================================================================================\n\
MSG: delivery_robot/r_pose\n\
geometry_msgs/Point point\n\
r_angle angle\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: delivery_robot/r_angle\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
";
  }

  static const char* value(const ::delivery_robot::r_costmap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delivery_robot::r_costmap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resolution);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.origin);
      stream.next(m.cost_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct r_costmap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delivery_robot::r_costmap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delivery_robot::r_costmap_<ContainerAllocator>& v)
  {
    s << indent << "resolution: ";
    Printer<double>::stream(s, indent + "  ", v.resolution);
    s << indent << "width: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.height);
    s << indent << "origin: ";
    s << std::endl;
    Printer< ::delivery_robot::r_pose_<ContainerAllocator> >::stream(s, indent + "  ", v.origin);
    s << indent << "cost_value[]" << std::endl;
    for (size_t i = 0; i < v.cost_value.size(); ++i)
    {
      s << indent << "  cost_value[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.cost_value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELIVERY_ROBOT_MESSAGE_R_COSTMAP_H
