obstacle_range: 15.0
raytrace_range: 16.0

footprint: [[-0.240, -0.155], [-0.240, 0.155], [0.092, 0.155], [0.092, -0.155]] # 20201124_5cm拡張

#robot_radius: 0.17

inflation_layer:
  inflation_radius: 0.4
  cost_scaling_factor: 3.0

map_type: costmap

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: turtlebot_01/velodyne, data_type: LaserScan, topic: /turtlebot_01/scan_filtered, marking: true, clearing: true, inf_is_valid: true}
