global_costmap:
  global_frame: map
  robot_base_frame: turtlebot_01/base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 2.0

  static_map: true

  plugins:
       -
         name: static_layer
         type: "costmap_2d::StaticLayer" 
       - 
         name: obstacle_layer
         type: "costmap_2d::ObstacleLayer" 
       -
         name: multi_robot_layer
         type: "multi_robot_layer_namespace::MultiRobotLayer"
       - 
         name: inflation_layer
         type: "costmap_2d::InflationLayer"

