local_costmap:
  global_frame: turtlebot_01/odom
  robot_base_frame: turtlebot_01/base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 2.0

  static_map: false  
  rolling_window: true
  width: 2
  height: 2
  resolution: 0.05
  plugins:
       -
         name: static_layer
         type: "costmap_2d::StaticLayer" 
       - 
         name: obstacle_layer
         type: "costmap_2d::ObstacleLayer" 
       - 
         name: inflation_layer
         type: "costmap_2d::InflationLayer"

